name: Nabil Elqatib (marrakchino)
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-midnight
plugins:
    - jekyll-seo-tag
twitter:
    username: neqneqneq
    card: summary

tag_page: '/blog/tags.html'
